import { Role } from '../types/asset';

export type Permission =
  | 'ASSET_VIEW'
  | 'ASSET_CREATE'
  | 'ASSET_EDIT'
  | 'ASSET_DELETE'
  | 'INSPECTION_VIEW'
  | 'INSPECTION_CREATE'
  | 'INSPECTION_EDIT'
  | 'INSPECTION_APPROVE'
  | 'MAINTENANCE_VIEW'
  | 'MAINTENANCE_CREATE'
  | 'MAINTENANCE_EDIT'
  | 'MAINTENANCE_APPROVE'
  | 'WORK_ORDER_VIEW'
  | 'WORK_ORDER_CREATE'
  | 'WORK_ORDER_ASSIGN'
  | 'WORK_ORDER_UPDATE'
  | 'WORK_ORDER_CLOSE'
  | 'REPORT_VIEW'
  | 'REPORT_EXPORT'
  | 'USER_VIEW'
  | 'USER_CREATE'
  | 'USER_EDIT'
  | 'USER_DISABLE'
  | 'DASHBOARD_VIEW'
  | 'MAP_VIEW';

const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: [
    'ASSET_VIEW', 'ASSET_CREATE', 'ASSET_EDIT', 'ASSET_DELETE',
    'INSPECTION_VIEW', 'INSPECTION_CREATE', 'INSPECTION_EDIT', 'INSPECTION_APPROVE',
    'MAINTENANCE_VIEW', 'MAINTENANCE_CREATE', 'MAINTENANCE_EDIT', 'MAINTENANCE_APPROVE',
    'WORK_ORDER_VIEW', 'WORK_ORDER_CREATE', 'WORK_ORDER_ASSIGN', 'WORK_ORDER_UPDATE', 'WORK_ORDER_CLOSE',
    'REPORT_VIEW', 'REPORT_EXPORT',
    'USER_VIEW', 'USER_CREATE', 'USER_EDIT', 'USER_DISABLE',
    'DASHBOARD_VIEW', 'MAP_VIEW'
  ],
  RNB_ADMIN: [
    'ASSET_VIEW', 'ASSET_CREATE', 'ASSET_EDIT',
    'INSPECTION_VIEW', 'INSPECTION_CREATE', 'INSPECTION_EDIT', 'INSPECTION_APPROVE',
    'MAINTENANCE_VIEW', 'MAINTENANCE_CREATE', 'MAINTENANCE_EDIT', 'MAINTENANCE_APPROVE',
    'WORK_ORDER_VIEW', 'WORK_ORDER_CREATE', 'WORK_ORDER_ASSIGN', 'WORK_ORDER_UPDATE', 'WORK_ORDER_CLOSE',
    'REPORT_VIEW', 'REPORT_EXPORT',
    'DASHBOARD_VIEW', 'MAP_VIEW'
  ],
  ROAD_OFFICER: [
    'ASSET_VIEW', 'ASSET_CREATE', 'ASSET_EDIT',
    'INSPECTION_VIEW', 'INSPECTION_CREATE', 'INSPECTION_EDIT',
    'MAINTENANCE_VIEW', 'MAINTENANCE_CREATE', 'MAINTENANCE_EDIT',
    'WORK_ORDER_VIEW', 'WORK_ORDER_CREATE', 'WORK_ORDER_UPDATE',
    'REPORT_VIEW', 'REPORT_EXPORT',
    'DASHBOARD_VIEW', 'MAP_VIEW'
  ],
  BRIDGE_OFFICER: [
    'ASSET_VIEW', 'ASSET_CREATE', 'ASSET_EDIT',
    'INSPECTION_VIEW', 'INSPECTION_CREATE', 'INSPECTION_EDIT',
    'MAINTENANCE_VIEW', 'MAINTENANCE_CREATE', 'MAINTENANCE_EDIT',
    'WORK_ORDER_VIEW', 'WORK_ORDER_CREATE', 'WORK_ORDER_UPDATE',
    'REPORT_VIEW', 'REPORT_EXPORT',
    'DASHBOARD_VIEW', 'MAP_VIEW'
  ],
  BUILDING_OFFICER: [
    'ASSET_VIEW', 'ASSET_CREATE', 'ASSET_EDIT',
    'INSPECTION_VIEW', 'INSPECTION_CREATE', 'INSPECTION_EDIT',
    'MAINTENANCE_VIEW', 'MAINTENANCE_CREATE', 'MAINTENANCE_EDIT',
    'WORK_ORDER_VIEW', 'WORK_ORDER_CREATE', 'WORK_ORDER_UPDATE',
    'REPORT_VIEW', 'REPORT_EXPORT',
    'DASHBOARD_VIEW', 'MAP_VIEW'
  ],
  FIELD_OFFICER: [
    'ASSET_VIEW',
    'INSPECTION_VIEW', 'INSPECTION_CREATE',
    'MAINTENANCE_VIEW',
    'WORK_ORDER_VIEW', 'WORK_ORDER_UPDATE',
    'DASHBOARD_VIEW', 'MAP_VIEW'
  ]
};

export function hasPermission(role: Role | undefined, permission: Permission): boolean {
  if (!role) return false;
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permission);
}
